import { Activity, Clock3, Filter, Search, ShieldAlert, Target, UserRoundCheck, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { reviewQueue } from "@/data/averis-data";
import { Button } from "@/components/ui/button";
import { StatCard } from "@/components/stat-card";

type QueueFilter = "all" | "high" | "review";

export function ReviewScreen() {
  const [filter, setFilter] = useState<QueueFilter>("all");
  const [query, setQuery] = useState("");
  const [open, setOpen] = useState<string | null>(null);
  const items = useMemo(() => reviewQueue.filter((item) => (filter === "all" || (filter === "high" ? item.priority === "high" : item.requiresReview)) && `${item.id} ${item.reference} ${item.issue}`.toLowerCase().includes(query.toLowerCase())), [filter, query]);
  return (
    <section>
      <div className="flex flex-wrap items-start justify-between gap-4"><header><h1 className="text-2xl font-extrabold">Review</h1><p className="mt-1 text-sm text-muted-foreground">Audit and resolve discrepancies in high-priority freight documents.</p></header><div className="flex rounded-lg border border-border bg-card p-1 shadow-sm">{([["all", "All (4)"], ["high", "High Priority (2)"], ["review", "Requires Review (2)"]] as const).map(([value, label]) => <Button key={value} size="sm" variant={filter === value ? "primary" : "ghost"} onClick={() => setFilter(value)}>{label}</Button>)}</div></div>
      <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Urgent actions" value="Critical Path" icon={ShieldAlert} note="2 items" /><StatCard label="Avg. review time" value="42m 15s" icon={Clock3} tone="warning" /><StatCard label="Accuracy rate" value="99.2%" icon={Target} tone="success" /><StatCard label="Active reviewers" value="8 Online" icon={Users} tone="info" /></div>
      <div className="mt-6 flex items-center gap-3 rounded-lg border border-border bg-card p-3 shadow-sm"><label className="flex h-10 max-w-md flex-1 items-center gap-2 rounded-md border border-border bg-background px-3 text-muted-foreground"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full bg-transparent text-sm outline-none" placeholder="Search by reference, carrier, or ship name..." /></label><span className="ml-auto hidden text-xs font-semibold text-muted-foreground md:block">Sort: <b className="text-foreground">Priority (High–Low)</b></span><Button size="icon" variant="ghost" aria-label="Filter queue"><Filter size={16} /></Button></div>
      <div className="mt-5 space-y-3">{items.map((item) => <div key={item.id} className="overflow-hidden rounded-lg border border-border bg-card shadow-sm"><button onClick={() => setOpen(open === item.id ? null : item.id)} className="grid w-full grid-cols-[auto_1fr] items-center gap-4 p-4 text-left md:grid-cols-[auto_110px_1fr_2fr_1fr_90px_auto]"><span className={`flex size-9 items-center justify-center rounded-full ${item.priority === "high" ? "bg-primary/10 text-primary" : "bg-muted text-muted-foreground"}`}><ShieldAlert size={16} /></span><span><b className="block text-sm">{item.id}</b><small className="text-[9px] font-extrabold uppercase text-muted-foreground">{item.priority} priority</small></span><span className="hidden md:block"><small className="block text-[9px] font-extrabold uppercase text-muted-foreground">Reference</small><b className="text-sm">{item.reference}</b></span><span className="hidden md:block"><small className="block text-[9px] font-extrabold uppercase text-muted-foreground">Issue description</small><b className="text-sm">{item.issue}</b></span><span className="hidden text-right md:block"><small className="block text-[9px] font-extrabold uppercase text-muted-foreground">Assignee</small><b className="text-sm">{item.assignee}</b></span><span className="hidden md:block"><small className="block text-[9px] font-extrabold uppercase text-muted-foreground">Pending time</small><b className="text-sm">{item.pending}</b></span><span className="text-muted-foreground">⌄</span></button>{open === item.id && <div className="grid gap-4 border-t border-border bg-muted/30 p-5 md:grid-cols-[1fr_auto]"><div><p className="text-xs font-extrabold uppercase text-muted-foreground">Review context</p><p className="mt-2 text-sm">{item.issue}. Check the related shipping instruction and bill of lading values before resolving this queue item.</p></div><div className="flex items-center gap-2"><Button size="sm">Assign</Button><Button size="sm" variant="primary"><UserRoundCheck size={14} />Open comparison</Button></div></div>}</div>)}</div>
      <div className="mt-8 flex items-center justify-between text-xs text-muted-foreground"><span>Displaying <b className="text-foreground">{items.length}</b> active tasks</span><span className="flex items-center gap-2 uppercase tracking-widest"><Activity size={13} /> End of queue</span></div>
    </section>
  );
}